### ISSUE TITLE
Tinkers' Construct crashing with ManaMetalMod

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/TinkersConstruct#129]
### Your Pack Version

Custom

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Hi! i was trying to play Tinkers' Construct with ManaMetalMod, however game crashing when i create survival world, or using /gamemode 0
I know its might be M3 problem but Tinkers' Construct does something with tconstruct.client.HealthBarRenderer

### Crash Report

https://mclo.gs/ED8JB77

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
This is an issue in ManaMetal:

TiCon emits an `RenderGameOverlayEvent.Post:
https://github.com/GTNewHorizons/TinkersConstruct/blob/e292d4cad9039de28c0f06d347ee388d9f07d8dd/src/main/java/tconstruct/client/HealthBarRenderer.java#L190

which is not cancelable:
https://github.com/MinecraftForge/MinecraftForge/blob/9274e4fe435cb415099a8216c1b42235f185443e/src/main/java/net/minecraftforge/client/event/RenderGameOverlayEvent.java#L72

ManaMetal's handler which receives this event tries to cancel it without checking if it's allowed (via `#isCancelable()`):
```java
@SubscribeEvent
public void onGame(RenderGameOverlayEvent event) {
    if (event.type == ElementType.HEALTH) {
        event.setCanceled(true);
    }

    if (event.type == ElementType.BOSSHEALTH) {
        event.setCanceled(true);
    }
}
```
(decompiled source in `project/studio/manametalmod/event/EventGUI`)

Calling `#setCanceled()` on an uncancelable event throws an IllegalArgumentException.
