### ISSUE TITLE
Game crashes when I try casting gold

### ISSUE THREAD

**Issue by mmiovv2** [GTNewHorizons/TinkersConstruct#131]
Crash report: https://mclo.gs/ydOIIdw

**Comment by chochem** [comment]
more details would be useful.
- modversion/modpack context
- what exactly are you casting
- is it repeatable or one off?

**Comment by mmiovv2** [comment]
> more details would be useful.
> 
> * modversion/modpack context
> * what exactly are you casting
> * is it repeatable or one off?

- custom pack
- gold into an empty table
- repeatable
