### ISSUE TITLE
Oreberry oredict bug: gold oreberry has 2 confilct ore dict tags while exp oreberry has none

### ISSUE THREAD

**Issue by Apeiria01** [GTNewHorizons/TinkersConstruct#137]
### Mod Version

master

### Bug Report

TinkerWorld.java Line 983:
OreDictionary.registerOre("oreberryGold", new ItemStack(TinkerWorld.oreBerries, 1, 1));
OreDictionary.registerOre("oreberryEssence", new ItemStack(TinkerWorld.oreBerries, 1, 1));

In ore dictionary gold oreberry registered with both gold oreberry and exp oreberry tag

### Java Version

Java 17

### Mod List or GTNH Pack Version

gtnh 2.6.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by wlhlm** [comment]
Thanks for the report. Since you did pretty much all the work, feel free to make a pull request next time for proper attribution.
